server:
  port: 8001
  servlet:
    encoding:
      charset: utf-8

spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/test9doitdb
    driver-class-name: org.mariadb.jdbc.Driver
    username: test9doit
    password: 423206

    output:
    ansi:
      enabled: always

logging:
  level:
    '[org.springframework.boot.web]': INFO
    '[site.metacoding.miniproject2]': DEBUG