server:
  port: 8000
  servlet:
    encoding:
      charset: utf-8

spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/9doitdb
    driver-class-name: org.mariadb.jdbc.Driver
    username: 9doit
    password: 423206

    output:
    ansi:
      enabled: always

logging:
  level:
    '[org.hibernate.SQL]': DEBUG
    '[site.metacoding.miniproject2]': DEBUG